[workspace]
members = ["core","xtask"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["fluxdiv <156196590+fluxdiv@users.noreply.github.com>"]
publish = false

[workspace.dependencies]
anyhow = "1.0.82"
dirs = "5.0"
