[package]
name = "xtask"
description = "Based on https://github.com/matklad/cargo-xtask"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
dirs = { workspace = true }
anyhow = { workspace = true }
